export const communityData = [
  {
    id: 1,
    username: "Dr. Arjun Singh",
    role: "Psychiatrist",
    qualification: "Neurologist",
    experience: "29 years",
    registration: "MCR244618",
    facility: "LifeCare Hospital,123 Main St, City A",
    email: "consultant 1@hotmail.com",
    phone: "+91 2785593065",
    name: "Dr. Arjun Singh",
  },
  {
    id: 2,
    username: "Dr. Kavita Sharma",
    role: "Orthopedic",
    qualification: "Oncologist",
    experience: "9 years",
    registration: "MCR407923",
    facility: "Sunrise Hospital,123 Main St, City A",
    email: "medical 2@gmail.com",
    phone: "+91 6265868599",
    name: "Dr. Kavita Sharma",
  },
  {
    id: 3,
    username: "Dr. Ramesh Gupta",
    role: "Psychiatrist",
    qualification: "Psychiatrist",
    experience: "7 years",
    registration: "MCR449583",
    facility: "Prime Health Center,123 Main St, City A",
    email: "specialist 3@outlook.com",
    phone: "+91 9119707573",
    name: "Dr. Ramesh Gupta",
  },
  {
    id: 4,
    username: "Dr. Meena Verma",
    role: "Surgeon",
    qualification: "Cardiologist",
    experience: "35 years",
    registration: "MCR959595",
    facility: "Sunrise Hospital,123 Main St, City A",
    email: "dr. 4@live.com",
    phone: "+91 0260784794",
    name: "Dr. Meena Verma",
  },
  {
    id: 5,
    username: "Dr. Aakash Patel",
    role: "Oncologist",
    qualification: "Gynecologist",
    experience: "46 years",
    registration: "MCR637456",
    facility: "Nihal's Homecare,123 Main St, City A",
    email: "consultant 5@live.com",
    phone: "+91 6055861371",
    name: "Dr. Aakash Patel",
  },
  {
    id: 6,
    username: "Dr. Priya Nair",
    role: "Surgeon",
    qualification: "Dermatologist",
    experience: "20 years",
    registration: "MCR450969",
    facility: "Healing Hands,123 Main St, City A",
    email: "consultant 6@live.com",
    phone: "+91 5013992088",
    name: "Dr. Priya Nair",
  },
  {
    id: 7,
    username: "Dr. Vikram Sinha",
    role: "Doctor",
    qualification: "General Physician",
    experience: "8 years",
    registration: "MCR407025",
    facility: "Nihal's Homecare,123 Main St, City A",
    email: "dr. 7@gmail.com",
    phone: "+91 6578767623",
    name: "Dr. Vikram Sinha",
  },
  {
    id: 8,
    username: "Dr. Nisha Rao",
    role: "Neurologist",
    qualification: "Cardiologist",
    experience: "9 years",
    registration: "MCR623415",
    facility: "Healing Hands,123 Main St, City A",
    email: "doctor 8@yahoo.com",
    phone: "+91 7964110534",
    name: "Dr. Nisha Rao",
  },
  {
    id: 9,
    username: "Dr. Anil Kumar",
    role: "Gynecologist",
    qualification: "Pediatrician",
    experience: "48 years",
    registration: "MCR600301",
    facility: "Sunrise Hospital,123 Main St, City A",
    email: "doctor 9@yahoo.com",
    phone: "+91 0359378437",
    name: "Dr. Anil Kumar",
  },
  {
    id: 10,
    username: "Dr. Shweta Jain",
    role: "Surgeon",
    qualification: "Neurologist",
    experience: "33 years",
    registration: "MCR385578",
    facility: "Global Health,123 Main St, City A",
    email: "medical 10@gmail.com",
    phone: "+91 8776825863",
    name: "Dr. Shweta Jain",
  },
];
