export const facilitiesData = [
  {
    name: "Manipal Hospital",
    district: "Bengaluru",
    taluk: "Bengaluru South",
    location: "HAL Airport Road, Kodihalli, Bengaluru, Karnataka 560017",
    type: "Private Hospital",
    phone: "+91 80401 80000",
    occupancy: "300",
  },
  {
    name: "Narayana Health City",
    district: "Bengaluru",
    taluk: "Anekal",
    location: "Industrial Area, Hosur Road, Bengaluru, Karnataka 560099",
    type: "Private Hospital",
    phone: "+91 80671 66666",
    occupancy: "450",
  },
  {
    name: "St. John's Medical College Hospital",
    district: "Bengaluru",
    taluk: "Bengaluru South",
    location: "Sarjapur Main Road, Koramangala, Bengaluru, Karnataka 560034",
    type: "Private Hospital",
    phone: "+91 80220 65000",
    occupancy: "100",
  },
  {
    name: "Victoria Hospital",
    district: "Bengaluru",
    taluk: "Bengaluru South",
    location: "K.R. Market, Fort, Bengaluru, Karnataka 560002",
    type: "Government Hospital",
    phone: "+91 80267 01511",
    occupancy: "600",
  },
  {
    name: "Kasturba Hospital",
    district: "Udupi",
    taluk: "Manipal",
    location: "Madhav Nagar, Manipal, Karnataka 576104",
    type: "Private Hospital",
    phone: "+91 82029 22222",
    occupancy: "250",
  },
  {
    name: "Sri Jayadeva Institute of Sciences and Research",
    district: "Bengaluru",
    taluk: "Bengaluru South",
    location:
      "Bannerghatta Road, 9th Block, Jayanagar, Bengaluru, Karnataka 560069",
    type: "Government Hospital",
    phone: "+91 80229 77200",
    occupancy: "200",
  },
  {
    name: "Apollo Hospital",
    district: "Mysuru",
    taluk: "Mysuru",
    location: "No. 1, Abba Road, Nazarbad, Mysuru, Karnataka 570007",
    type: "Private Hospital",
    phone: "+91 82125 67890",
    occupancy: "500",
  },
  {
    name: "S.S. Institute of Medical Sciences & Research Centre",
    district: "Davanagere",
    taluk: "Davanagere",
    location: "NH-4 Bypass Road, Davanagere, Karnataka 577005",
    type: "Private Hospital",
    phone: "+91 81922 22333",
    occupancy: "400",
  },
  {
    name: "BGS Global Hospital",
    district: "Bengaluru",
    taluk: "Kengeri",
    location:
      "No. 67, Uttarahalli Main Road, Kengeri, Bengaluru, Karnataka 560060",
    type: "Private Hospital",
    phone: "+91 80269 88888",
    occupancy: "500",
  },
  {
    name: "JSS Hospital",
    district: "Mysuru",
    taluk: "Mysuru",
    location: "M.G. Road, Agrahara, Mysuru, Karnataka 570004",
    type: "Private Hospital",
    phone: "+91 82125 48788",
    occupancy: "110",
  },
];
